# -*- coding: utf-8 -*-
"""Pregunta3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gysRKcGB0ab2PoeOoL3KQEMTmFMl-eFn
"""

def DiviRecu(Dividendo, Divisor):                           #(4, 2)
    if Dividendo < Divisor:
        return 0
    return 1 + DiviRecu(Dividendo - Divisor, Divisor)       #DyD


Dividendo = int(input("Ingresa el Dividendo: "))
divisor = int(input("Ingresa el Divisor: "))

if divisor == 0:
    print("ERROR!!!!! INGRESA NUMEROS POSITIVOS")
else:
    resultado = DiviRecu(Dividendo, divisor)
    print(f"El resultado de la división es: {resultado}")