# -*- coding: utf-8 -*-
"""Pregunta1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pnZD2tyRyY2DGGS0gFHCK1Q2nosV_XMR
"""

#DATOS:QUISPE CRISOSTOMO EDISON

def menu():
  while (True):
    print("""
    ===== BIENVENIDO A MI MENÚ =====
    a. OPCIÓN CONTAR CONSONANTES SIN VOCALES
    b. SALIR
    """)
    Opcion = input("Elige una Opción (a/b): ").lower()
    if Opcion == 'a':
      Palabra = input("Ingresa una Palabra: ").lower()
      Cantidad = ContarConsonante(Palabra)
      print(f"La Cantidad de Consonantes sin Vocales en '{Palabra}' es: {Cantidad}")
    elif Opcion == 'b':
        print("=== SALIENDO DEL MENÚ ===")
        break
    else:
        print("===== ERROR!!!!! Ingresa un Opcion Válida (a/b) =====")
menu()

def ContarConsonante(Palabra):
  Palabra = Palabra.lower()
  Consonantes = 'bcdfghjklmnpqrstvwxyz'
  Contador = 0
  for Letras in Palabra:
    if Letras in Consonantes:
      Contador += 1
  return Contador